## Hide unused HDMI/DP audio outputs (no monitor connected) and unused laptop mics

monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.pci-0000_c4_00.1.HiFi__HDMI3__sink" }
    ]
    actions = { update-props = { node.disabled = true } }
  }
  {
    matches = [
      { node.name = "alsa_output.pci-0000_c4_00.1.HiFi__HDMI2__sink" }
    ]
    actions = { update-props = { node.disabled = true } }
  }
  {
    matches = [
      { node.name = "alsa_output.pci-0000_c4_00.1.HiFi__HDMI1__sink" }
    ]
    actions = { update-props = { node.disabled = true } }
  }
  {
    matches = [
      { node.name = "alsa_input.pci-0000_c4_00.6.HiFi__Mic1__source" }
    ]
    actions = { update-props = { node.disabled = true } }
  }
  {
    matches = [
      { node.name = "alsa_input.pci-0000_c4_00.6.HiFi__Mic2__source" }
    ]
    actions = { update-props = { node.disabled = true } }
  }
]
